### ISSUE TITLE
Vitals API v3.1.2 vs REST API Sandbox EU

### ISSUE THREAD

**Issue by pmalirz** [tryVital/vital-node#62]
Hi Team,

First of all great project guys! I'm currently looking for a good wearable API for my project and exploring tryvital.io.
I'm facing some troubles though. I'm not sure if this auto-generated API reflects what is published in the EU Sandbox and covered by docs https://docs.tryvital.io/api-reference/body/get-summary.

Here is the issue I'm facing. The following call responds with an error:

```javascript
const request2: VitalsCaloriesActiveGroupedRequest = {
    startDate: "2024-03-07",
    endDate: "2024-03-07"
}

const data2 = vital.vitals.caloriesActiveGrouped(
    userId,
    request2
).then(value => {
    console.log(value);
});
```

it results with:
```bash
...\procjets\life-coin\node_modules\@tryvital\vital-node\core\schemas\builders\schema-utils\getSchemaUtils.js:5
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
                                                         ^
ParseError: response -> groups -> garmin -> [0] -> source: Missing required key "name"; response -> groups -> garmin -> [0] -> source: Missing required key "slug"; response -> groups -> garmin -> [0] -> source: Missing required key "logo"
    at ...\procjets\life-coin\node_modules\@tryvital\vital-node\core\schemas\builders\schema-utils\getSchemaUtils.js:25:19
    at Generator.next (<anonymous>)
    at fulfilled (...\procjets\life-coin\node_modules\@tryvital\vital-node\core\schemas\builders\schema-utils\getSchemaUtils.js:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errors: [
    { path: [Array], message: 'Missing required key "name"' },
    { path: [Array], message: 'Missing required key "slug"' },
    { path: [Array], message: 'Missing required key "logo"' }
  ]
}
```

What I noticed in the docs is that in the vitals API (https://docs.tryvital.io/api-reference/timeseries-grouped/blood-oxygen)
there is no REST for Grouped Calories.

Any help much appreciated.

Thank you
Przemek

**Comment by andersio** [comment]
Hi, there is a discrepancy in the schema that causes our SDK codegen to mis-handle some deprecated fields. We will look into this on Monday.

**Comment by pmalirz** [comment]
That would be helpful, thank you

**Comment by andersio** [comment]
This was addressed a couple days ago with our backend release. No new SDK release is needed.

**Comment by pmalirz** [comment]
Thank you @andersio
